name: update-html

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Run build script
        id: build
        run: |
          bash build.sh

          if git diff --exit-code --quiet; then
            echo "updated=0" >> $GITHUB_OUTPUT
          else
            echo "updated=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changes
        if: steps.build.outputs.updated == '1'
        run: |
          git config --global user.email "noreply@oss.acmcsuf.com"
          git config --global user.name "acmcsufoss"
          git commit -am "Update HTML"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
